services:

  mariadb:
    build: requirements/mariadb # path to the dockerfile
    container_name: mariadb
    env_file:
      - .env
      - ../secrets/.db_password.txt
      - ../secrets/.db_root_password.txt
      - ../secrets/.credentials.txt
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
      # networks are used to allow containers to communicate with each other

  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    ports:
      - "443:443"
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  wordpress:
    build: requirements/wordpress
    container_name: wp-php
    env_file:
      - ../secrets/.db_password.txt
      - ../secrets/.db_root_password.txt
      - ../secrets/.credentials.txt
      - .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    ports:
      - "8080:80"

  redis:
    build: requirements/redis
    container_name: redis
    depends_on:
      - mariadb
    ports:
      - "6379:6379"
    networks:
      - inception

  ftp:
    build: requirements/FTP
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception

  portainer:
    build: requirements/portainer
    container_name: portainer
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - inception

volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dboire/data/mysql
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/dboire/data/wordpress
  portainer_data:


networks:
  inception:
    driver: bridge
